bandit:
  version: AppSecPipeline 0.5.0
  tool-version:
  name: bandit
  tags:
    - "Static Code Analyzer"
  type: "static"
  description: "Bandit is a tool designed to find common security issues in Python code. To do this Bandit processes each file, builds an AST from it, and runs appropriate plugins against the AST nodes. Once Bandit has finished scanning all the files it generates a report."
  docker: "appsecpipeline/base-tools:1.8.5"
  url: https://wiki.openstack.org/wiki/Security/Projects/Bandit
  documentation: https://docs.openstack.org/bandit/latest/index.html
  parameters:
    LOC:
      type: runtime
      data_type: string
      description: "Location of the source code."
  commands:
    pre:
    exec: "bandit"
    shell: True
    report: "-f json -o {reportname}"
    reportname: "{timestamp}.json"
    post:
    junit:
  languages:
    - "python"
  profiles:
    #Runs the full bandit scan
    all: "-r $LOC"
    #Only the issues that are the highest severity and the highest confidence
    tuned: "-lll -iii -r $LOC"
