wappalyzer:
  version: AppSecPipeline 0.5.0
  tags:
    - "Dyanmic Scanner"
  type: "dynamic"
  scan_type: "web"
  icon-sm:
  icon-lg:
  description: "Wappalyzer is a cross-platform utility that uncovers the technologies used on websites. It detects content management systems, eCommerce platforms, web servers, JavaScript frameworks, analytics tools and many more."
  url: https://www.wappalyzer.com/
  documentation: https://github.com/AliasIO/Wappalyzer
  docker: "appsecpipeline/node:1.3.0"
  parameters:
    URL:
      type: runtime
      data_type: url
      description: "URL of the site to scan."
  commands:
    pre:
    exec: "cd /usr/local/lib/node_modules/wappalyzer && node index.js $URL"
    shell: True
    report: "> {reportname}"
    reportname: "{timestamp}.json"
    post:
    junit:
  profiles:
    all: " "
